### PR TITLE
expand stock type struct to hold details

### PR DESCRIPTION
**Pull request by sgravitz**
add view=detail to URL. expand stock type struct to hold details. Add
sample json response as comment.

Modified public member comments in stock.go to pass goLint

### CODE REVIEW

**Comment by vic3lord** [comment]
The String() method should print the entire object as it implements string and GetByIndex shouldn't act as a String()

**Comment by sgravitz** [comment]
Thanks - I realized example1 and example2 don't work. First of all, you can't have 2 func main in the same sub-folder - and I also had to switch the stock import from your account to my account, effectively breaking the examples for you. I have an idea on how to restructure the samples - but won't be able to get to it until later today.

**Comment by sgravitz** [comment]
And I agree with you about String().

**Comment by vic3lord** [comment]
@sgravitz regarding the examples folder, it is suppose to just hold files and show how to work with this library, and you can run them with `go run example1.go`

This will run with multiple main funcs

**Pull request merged**
